<?php
/**
 * index page for the example
 */
?>
<h1><?php echo $title ?></h1>

<p>
    Welcome! You are looking at home page of the example, and the value of $foo is:
    <code><?php print_r($foo); ?></code>
</p>

<p>
    This page is rendered from <pre><?php var_dump($this) ?></pre>
</p>

<a href="/" class="btn btn-default">default layout</a> <a href="/newLayout" class="btn btn-danger">new layout</a>
